/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

/**
 *
 * @author ANSHIKA
 */

import com.mysql.cj.util.StringUtils;
import java.sql.*;

import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class EditAgent extends javax.swing.JFrame {

    /**
     * Creates new form EditAgent
     */
    public EditAgent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        updateAgentId = new javax.swing.JTextField();
        proceedUpdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        deleteAgentID = new javax.swing.JTextField();
        newAgent = new javax.swing.JButton();
        proceedDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Enter Agent_Id:");

        updateAgentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAgentIdActionPerformed(evt);
            }
        });

        proceedUpdate.setText("Next");
        proceedUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedUpdateActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Enter Agent_Id:");

        deleteAgentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAgentIDActionPerformed(evt);
            }
        });

        newAgent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newAgent.setText("New +");
        newAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAgentActionPerformed(evt);
            }
        });

        proceedDelete.setText("Delete");
        proceedDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("<HTML><U>Add Agent</U><HTML>");

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("<HTML><U>Update Agent</U><HTML>");

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("<HTML><U>Delete Agent</U><HTML>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(proceedUpdate)
                .addGap(363, 363, 363))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(newAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateAgentId, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(522, 522, 522)
                            .addComponent(proceedDelete))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(198, 198, 198)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(deleteAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateAgentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(proceedUpdate)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(deleteAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(proceedDelete)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateAgentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAgentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateAgentIdActionPerformed

    private void proceedUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedUpdateActionPerformed
        if(updateAgentId.getText().isBlank() || updateAgentId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "EstateId can't be empty!",
                "Unsuccesfull", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int text_size = 30;

        JTextField First_Name = new JTextField(text_size);
        JTextField Last_Name = new JTextField(text_size);
        JTextField Agent_ContactNo = new JTextField(text_size);

        JPanel agentPannel = new JPanel(new GridLayout(0,1));

        agentPannel.add(new JLabel("First Name:"));
        agentPannel.add(First_Name);

        agentPannel.add(new JLabel("Last Name:"));
        agentPannel.add(Last_Name);

        agentPannel.add(new JLabel("contact NO:"));
        agentPannel.add(Agent_ContactNo);

        int result = JOptionPane.showConfirmDialog(null, agentPannel,
            "Please Enter New Updated Estate details", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            if(!(
                First_Name.getText().isBlank()  || First_Name.getText().isEmpty() ||
                Last_Name.getText().isBlank()  || Last_Name.getText().isEmpty() ||
                Agent_ContactNo.getText().isBlank()  || Agent_ContactNo.getText().isEmpty()
            )) {

                updateAgent(
                    updateAgentId.getText(),
                    First_Name.getText(),
                    Last_Name.getText(),
                    Agent_ContactNo.getText()
                );

            }

            else {

                JOptionPane.showMessageDialog(this, "All attributes are mandatory!",
                    "Unsuccesfull", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_proceedUpdateActionPerformed

    private void deleteAgentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAgentIDActionPerformed

    }//GEN-LAST:event_deleteAgentIDActionPerformed

    private void newAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAgentActionPerformed

        // creating dialog box for taking input of estae attributes

        int text_size = 30;

        JTextField AgentID = new JTextField(text_size);
        JTextField FirstName = new JTextField(text_size);
        JTextField LastName = new JTextField(text_size);
        JTextField AgentContactNo = new JTextField(text_size);

        JPanel agentPannel = new JPanel(new GridLayout(0,1));
        agentPannel.add(new JLabel("AgentId:"));
        agentPannel.add(AgentID);

        agentPannel.add(new JLabel("First name:"));
        agentPannel.add(FirstName);

        agentPannel.add(new JLabel("Last Name:"));
        agentPannel.add(LastName);

        agentPannel.add(new JLabel("Contact No:"));
        agentPannel.add(AgentContactNo);


        int result = JOptionPane.showConfirmDialog(null, agentPannel,
            "Please Enter Estate details", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            if(!(
                AgentID.getText().isBlank()  || AgentID.getText().isEmpty() ||
                FirstName.getText().isBlank()  || FirstName.getText().isEmpty() ||
                LastName.getText().isBlank()  || LastName.getText().isEmpty() ||
                AgentContactNo.getText().isBlank()  || AgentContactNo.getText().isEmpty()
            )) {
                    addAgent(
                        AgentID.getText(), FirstName.getText(),
                        LastName.getText(), AgentContactNo.getText()
                    );

            }
            
            else {

                JOptionPane.showMessageDialog(this, "All attributes are mandatory!",
                    "Unsuccesfull", JOptionPane.ERROR_MESSAGE);

            }

        }

    }//GEN-LAST:event_newAgentActionPerformed

    private void proceedDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedDeleteActionPerformed
        if(deleteAgentID.getText().isBlank() || deleteAgentID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "EstateId can't be empty!",
                "Unsuccesfull", JOptionPane.ERROR_MESSAGE);
            return;
        }
        deleteAgent(deleteAgentID.getText());
    }//GEN-LAST:event_proceedDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAgent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deleteAgentID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton newAgent;
    private javax.swing.JButton proceedDelete;
    private javax.swing.JButton proceedUpdate;
    private javax.swing.JTextField updateAgentId;
    // End of variables declaration//GEN-END:variables

private boolean addAgent(String AgentId, String First_Name, String Last_Name,
            String Agent_Contact_No) {
        
       String insert_query = "Insert into agent values(?,?,?,?)";
        
        try {
            
            PreparedStatement stmt = Database.connection.prepareStatement(insert_query);
            
            stmt.setString(1, AgentId);    stmt.setString(2, First_Name);    stmt.setString(3, Last_Name);
            stmt.setString(4, Agent_Contact_No);
            
            System.out.println("row affected: " + stmt.executeUpdate());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Unsuccesfull", JOptionPane.ERROR_MESSAGE);
            return false;
        }
       
        return true;
    }

    
    private void updateAgent(String AgentId, String First_Name, String Last_Name,
            String Agent_Contact_No) {
        String update_query = "Update agent set First_Name = ? , Last_Name = ?, Agent_Contact_No = ? where Agent_Id = ?";
        int rowsAffected = 0;
        try {
            
            PreparedStatement stmt = Database.connection.prepareStatement(update_query);
            
            stmt.setString(1, First_Name);    stmt.setString(2, Last_Name);
            stmt.setString(3, Agent_Contact_No);    stmt.setString(4, AgentId);
            rowsAffected = stmt.executeUpdate();
            System.out.println("row affected: " + rowsAffected);
            JOptionPane.showMessageDialog(this, "rows: affected: " + rowsAffected , "succesfull", JOptionPane.OK_OPTION);
            updateAgentId.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Unsuccesfull", JOptionPane.ERROR_MESSAGE);
        }
        
       
    }

    private void deleteAgent(String AgentId) {
        //TODO
    }

}
