/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

/**
 *
 * @author ANSHIKA
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        handleOtions();
    }
    
    void handleOtions() {
        hideOptions();
        if(Database.role.equals("admin")) {
            editAgent.setVisible(true);
            editEstate.setVisible(true);
            viewEstate.setVisible(true);
            assignAgentToEstate.setVisible(true);
            addContract.setVisible(true);
            agentStatistics.setVisible(true);
        }
        else if(Database.role.equals("office")) {
            viewEstate.setVisible(true);
            agentStatistics.setVisible(true);
        }
        else if(Database.role.equals("agent")) {
            viewEstate.setVisible(true);
            addContract.setVisible(true);
        }
        else {
            System.out.println("Invalid user type: " + Database.role);
            System.exit(0);
        }
    }
    
    void hideOptions() {
        editAgent.setVisible(false);
        editEstate.setVisible(false);
        assignAgentToEstate.setVisible(false);
        viewEstate.setVisible(false);
        addContract.setVisible(false);
        agentStatistics.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewEstate = new javax.swing.JButton();
        editEstate = new javax.swing.JButton();
        editAgent = new javax.swing.JButton();
        assignAgentToEstate = new javax.swing.JButton();
        addContract = new javax.swing.JButton();
        agentStatistics = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewEstate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewEstate.setText("View Estate");
        viewEstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEstateActionPerformed(evt);
            }
        });

        editEstate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editEstate.setText("Edit Estate");
        editEstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEstateActionPerformed(evt);
            }
        });

        editAgent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editAgent.setText("Edit Agents");
        editAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAgentActionPerformed(evt);
            }
        });

        assignAgentToEstate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        assignAgentToEstate.setText("Assign Agent To Estate");
        assignAgentToEstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignAgentToEstateActionPerformed(evt);
            }
        });

        addContract.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addContract.setText("Add Contract");
        addContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContractActionPerformed(evt);
            }
        });

        agentStatistics.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        agentStatistics.setText("Agent Statistics");
        agentStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentStatisticsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewEstate, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agentStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addContract, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editEstate, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignAgentToEstate, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewEstate, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editEstate, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignAgentToEstate, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addContract, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agentStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewEstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEstateActionPerformed
        
        new SearchFrame().setVisible(true);
    }//GEN-LAST:event_viewEstateActionPerformed

    private void editEstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEstateActionPerformed
        
        new EditEstate().setVisible(true);
    }//GEN-LAST:event_editEstateActionPerformed

    private void editAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAgentActionPerformed
        
        new EditAgent().setVisible(true);
    }//GEN-LAST:event_editAgentActionPerformed

    private void assignAgentToEstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignAgentToEstateActionPerformed
        
        new AssignAgent().setVisible(true);
    }//GEN-LAST:event_assignAgentToEstateActionPerformed

    private void addContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContractActionPerformed
        new AddContract().setVisible(true);
    }//GEN-LAST:event_addContractActionPerformed

    private void agentStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentStatisticsActionPerformed
        // TODO add your handling code here:
        new Office().setVisible(true);
    }//GEN-LAST:event_agentStatisticsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addContract;
    private javax.swing.JButton agentStatistics;
    private javax.swing.JButton assignAgentToEstate;
    private javax.swing.JButton editAgent;
    private javax.swing.JButton editEstate;
    private javax.swing.JButton viewEstate;
    // End of variables declaration//GEN-END:variables
}
